### PR TITLE
add blahaj model to override totem of undying

### PR DESCRIPTION
**Pull request by zokibun**

### CODE REVIEW

**Comment by BatteryVoltic** [comment]
javaw_2023-10-07_23-03-22
Broken Texture, bad reference in 16000-blahaj.json in the custom model folder. Sending a fix.

**Comment by BatteryVoltic** [comment]
Fixed the texture calling
javaw_2023-10-07_23-06-36

**Review by FireBall1725 — CHANGES_REQUESTED** [review]
Can we uses 4 spaces instead of tabs please

**Comment by BatteryVoltic** [comment]
That is how block bench generates the files. If you look at the top of the file it states made with block bench. I will go in and make the changes really quick

**Review by FireBall1725 — APPROVED** [review]

**Pull request merged**
